# Generated by Django 4.2.1 on 2023-05-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(default="24.05.2023 19:46:26"),
        ),
    ]
